### ISSUE TITLE
这个地方Pandas和np改了一点，float和 dt.isocalendar().week.to_numpy()

### ISSUE THREAD

**Issue by huangzhaor** [yfzhang114/OneNet#1]
if timeenc == 2:
        dt = pd.to_datetime(dates.date.values)
        return np.stack([
            dt.minute.to_numpy(),
            dt.hour.to_numpy(),
            dt.dayofweek.to_numpy(),
            dt.day.to_numpy(),
            dt.dayofyear.to_numpy(),
            dt.month.to_numpy(),
            dt.isocalendar().week.to_numpy()
        ], axis=1).astype(float)

**Comment by yfzhang114** [comment]
Thanks!
