### ISSUE TITLE
Regarding the results of the paper

### ISSUE THREAD

**Issue by catcatwang** [yfzhang114/OneNet#2]
Thank you for your contribution. But when I tried to reproduce your code multiple times, I got results different from the article. When the prediction step size was 1 in the ETTh2 dataset, I got a result of 0.660 0.435. When the prediction step size was 24 in the WTH dataset, I got a result of 0.192 0.272. When I ran it on the ECL dataset, I got a result of 2.394 0.273, 2.324 0.360, 3.089 0.382. What is the reason?

**Comment by yfzhang114** [comment]
Ensure that you obtain results for baselines like FSNet. Currently, the results in ETTh2 appear to be inferior to all baselines, which is unexpected. Consider investigating and addressing this discrepancy.
